demo_all and demo_gitlab use cases
Dynatrace/ace-box pull request #204
Opened 2022-07-20 11:47 UTC by kristofre

fixes #193 #200

2022-07-21 08:15 UTC, tobigremmer-dt commented on dashboard/Dockerfile
> +RUN chmod -R 777 /app
Out of curiosity, what's the reason this is added?

2022-07-21 08:22 UTC, tobigremmer-dt commented on user-skel/ansible/roles/config-v2/tasks/main.yml
> +- name: Enable "demo_all"
This part is legacy logic (my bad...). Persisting whether a use case is enabled or not should be responsibility of the use case itself. Can we please add this to the demo all and demo gitlab roles? For example: https://github.com/Dynatrace/ace-box/blob/be5be01c7289aa127f317657f7f474328f26ee04/user-skel/ansible/roles/hot-incident-management/tasks/main.yml#L2

2022-07-21 08:22 UTC, tobigremmer-dt commented on user-skel/ansible/roles/config-v2/tasks/main.yml
> +- name: Enable "demo_gitlab"
Same as earlier. Can we please add this to the demo gitlab role?

2022-07-21 08:28 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-all/defaults/main.yml
> +---
These values should be set by config-v2 -> set-var so they are persisted and not overwritten by later `ace enable <different use case>`. We have two options:

1) Include config-v2 -> set-var in demo all main.yml
2) Cleaner and would remove earlier mentioned legacy code, config-v2 -> set-var is moved to respective use case roles (demo_default, demo_appsec, ...)

2022-07-21 08:30 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-gitlab/defaults/main.yml
> +gitlab_demo_default_repo_name: "ace"
Do we need both demo_default_... and gitlab_demo_default... variables or can they be consolidated?

2022-07-21 08:31 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitlab/tasks/ensure-project.yml
> +    gitlab_new_repo_created: false
This is probably not needed here?

2022-07-21 08:36 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitlab/tasks/create-organization.yml
> +---
create-organization and ensure-project are pretty much doing the same for different resources. Any chance code and file name can be changed to a common structure? E.g. filename create-organization.yml & create-project.yml or ensure-organization.yml & ensure-project.yml or ...

2022-07-21 08:36 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitlab/tasks/ensure-project.yml
> +---
create-organization and ensure-project are pretty much doing the same for different resources. Any chance code and file name can be changed to a common structure? E.g. filename create-organization.yml & create-project.yml or ensure-organization.yml & ensure-project.yml or ...

2022-07-21 08:39 UTC, tobigremmer-dt commented on user-skel/ansible/roles/keptn/tasks/main.yml
> +
Would be cleaner if this is set right when Keptn is deployed as Helm chart value, i.e.:

```
- name: Deploy Keptn on Kubernetes cluster
  kubernetes.core.helm:
    name: keptn
    chart_ref: "https://github.com/keptn/keptn/releases/download/{{ keptn_version }}/keptn-{{ keptn_version }}.tgz"
    release_namespace: "{{ keptn_namespace }}"
    create_namespace: true
    wait: true
    wait_timeout: 15m
    values:
      control-plane:
        bridge:
          lookAndFeelUrl: "{{ keptn_look_and_feel_url }}"
  register: keptn_helm_chart
```

2022-07-21 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitlab/tasks/configure.yml
> +# - include_tasks: roles/gitlab/tasks/ensure-project.yml
Can we remove this right away instead of commenting it out?

2022-07-21 08:57 UTC, tobigremmer-dt commented on user-skel/repos/ace/dynatrace/dynatrace.attachrules.yaml
>  attachRules:
I can't find where this file is used. Where is it still in use?

2022-07-21 09:00 UTC, tobigremmer-dt commented on user-skel/repos/ace/helm/simplenodeservicecanary/Chart.yaml
> +apiVersion: v1
How do you feel about using the same Helm Chart for both canary and non-canary use cases? Would reduce code duplication...

2022-07-21 09:01 UTC, tobigremmer-dt requested changes
Added a view comments. Everything else is looking good.

2022-07-21 14:46 UTC, kristofre commented on dashboard/Dockerfile
> +RUN chmod -R 777 /app
I was having permissions issues on the /app directory when building the image

2022-07-21 14:48 UTC, kristofre commented on user-skel/ansible/roles/gitlab/tasks/create-organization.yml
> +---
Correct, this one is also not used and can therefor be deleted

2022-07-21 14:50 UTC, kristofre commented on user-skel/repos/ace/dynatrace/dynatrace.attachrules.yaml
>  attachRules:
used by the gitlab event library

2022-07-21 14:51 UTC, kristofre commented on user-skel/repos/ace/helm/simplenodeservicecanary/Chart.yaml
> +apiVersion: v1
correct, I would see that as an enhancement and not for this PR

2022-07-21 14:53 UTC, kristofre commented on user-skel/ansible/roles/config-v2/tasks/main.yml
> +- name: Enable "demo_all"
So adding that is sufficient? Did a push against the branch

2022-07-21 15:07 UTC, kristofre commented on user-skel/ansible/roles/gitlab/tasks/ensure-project.yml
> +---
create-org has been removed as not used, I went for the "ensure" model, I prefer that

2022-07-21 15:09 UTC, kristofre commented on user-skel/ansible/roles/gitlab/tasks/configure.yml
> +# - include_tasks: roles/gitlab/tasks/ensure-project.yml
removed

2022-07-21 15:33 UTC, kristofre commented on user-skel/ansible/roles/demo-gitlab/defaults/main.yml
> +gitlab_demo_default_repo_name: "ace"
removed unused vars

2022-07-21 15:57 UTC, kristofre commented on user-skel/ansible/roles/config-v2/tasks/main.yml
> +- name: Enable "demo_all"
done

2022-07-21 15:59 UTC, kristofre commented on user-skel/ansible/roles/keptn/tasks/main.yml
> +
done

2022-07-21 15:59 UTC, kristofre commented on user-skel/ansible/roles/config-v2/tasks/main.yml
> +- name: Enable "demo_gitlab"
done

2022-07-22 07:54 UTC, tobigremmer-dt commented
Resolves #208

2022-07-25 15:41 UTC, tobigremmer-dt approved these changes
Looks good!

2022-07-25 15:45 UTC, merged