232 - feature ansible role for deploying unguard from 232-from-dev branch
Dynatrace/ace-box pull request #317
Opened 2022-10-07 13:50 UTC by eemrdog

It includes below:

- ace cli with an option to install app-unguard
- Deploy unguard
- Configure and apply monaco for unguard
- Readme

2022-10-07 14:33 UTC, tobigremmer-dt commented on .gitignore
> +**/.infracost/*
For the future: Please add .gitignore items that only affect your local environment in your personal .gitignore file (see for example https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer )

2022-10-07 14:38 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-unguard/tasks/apply-dt-configuration.yml
> +- include_role:
Please don't deploy an active gate as part of an application but leave it up to the use case whether an active gate is needed for synthetic tests or e.g. a public location is used.

2022-10-07 14:40 UTC, tobigremmer-dt requested changes
I added some comments, the other parts look good.

2022-10-07 16:26 UTC, eemrdog commented on user-skel/ansible/roles/app-unguard/tasks/apply-dt-configuration.yml
> +- include_role:
If we deploy activegate on the use case, the user needs to consider "skip_synthetic_monitor" variable as well. Otherwise, active-gate might be deployed redundantly. In that case, the user needs to read the instructions carefully not to miss that point.

If we deploy activegate on the app role which already embeds particular monaco rules like synthetic which is dependent on activegate, the user does not need to think of another condition to deploy an activegate in the use case. If they need an activegate for another purpose, they can include this role again and in that case, ansible idempotency should help. 

But embedding a primary component role (e.g activegate) in another primary role does not look good as you stated. So, I will leave it in the use case.

- include_role:
    name: app-unguard
    tasks_from: apply-dt-configuration
  vars:
    skip_synthetic_monitor: "false"

2022-10-10 06:01 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-unguard/tasks/apply-dt-configuration.yml
> +- include_role:
Not sure if I can follow you. What I'm saying is that "skip_synthetic_monitor" should not determine whether or not an Active Gate is deployed. It's up to the user to decide whether:
- they need an Active Gate as part of their use case
- they re-use an existing Active Gate as part of their use case
- they configure the Active Gate to be used as a private Synthetic location as part of their use case
- they use a public Synthetic location as part of their use case

2022-10-10 08:54 UTC, eemrdog commented on .gitignore
> +**/.infracost/*
done

2022-10-10 09:03 UTC, eemrdog commented on user-skel/ansible/roles/app-unguard/tasks/apply-dt-configuration.yml
> +- include_role:
Yes right, "skip_synthetic_monitor" does not cover if it is with a private or public location, either. So, using this parameter to determine active gate deployment is not a good idea. I removed dt-activegate role from the unguard apply-dt-configuration task.

2022-10-10 09:11 UTC, tobigremmer-dt approved these changes
Looks good!

2022-10-10 09:29 UTC, merged