283 feature docs for curated roles
Dynatrace/ace-box pull request #320
Opened 2022-10-11 16:18 UTC by eemrdog

From the list below, I have completed the readme files of the roles except for Dashboard. Jenkins is also done but
would like to do a second review. Could you please review the completed ones and send your comments?

app-unguard --ok
app-easytravel --ok
dt-oneagent --ok
dt-activegate --ok
microk8s --ok
monaco --ok
gitea --ok
repository --ok
gitlab --ok
Jenkins -- ok but want to check again
Dashboard --not ok
keptn-cli --ok

2022-10-13 11:30 UTC, eemrdog commented
Could you please review all the roles readme below?

app-unguard --ok
app-easytravel --ok
dt-oneagent --ok
dt-activegate --ok
microk8s --ok
monaco --ok
gitea --ok
repository --ok
gitlab --ok
Jenkins -- ok
Dashboard --ok
keptn-cli --ok

2022-10-13 12:57 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-easytravel/Readme.md
> +    Easy Travel Aplication Specific:
Minor typo: `Easytravel application specific`

2022-10-13 12:58 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dashboard/Readme.md
> +This currated role can be used to install Acebox Dashboard on a kubernetes cluster.
As a convention, would be cool if `ACE-Box` is used.

2022-10-13 13:00 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dashboard/Readme.md
> +  ```
In addition to `useCases` there is also an option to add `extRefs`. See https://github.com/dynatrace-ace/ace-box-ext-template/blob/main/example_roles/my-use-case/templates/my-use-case-dashboard.yml.j2

2022-10-13 13:02 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dt-activegate/Readme.md
> +This currated role can be used to deploy Dynatrace Synthetic-enabled ActiveGate on the acebox.
As a convention, would be cool if ACE-Box is used.

2022-10-13 13:02 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dt-oneagent/Readme.md
> +This currated role can be used to deploy Dynatrace Oneagent on the acebox.
As a convention, would be cool if `ACE-Box` is used.

2022-10-13 13:05 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dt-oneagent/Readme.md
> +This currated role can be used to deploy Dynatrace Oneagent on the acebox.
Also, the role is actually deploying a Dynatrace k8s operator (which itself deployed OneAgents). Would be great if this is adjusted.

(Kristof created an issue to clean up naming https://github.com/Dynatrace/ace-box/issues/328 )

2022-10-13 14:25 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitea/Readme.md
> +#### "source-secret"
Can we list the actual variable names? E.g. `gitea_username`, ... . Same for sourcing endpoints.

2022-10-13 14:27 UTC, tobigremmer-dt commented on user-skel/ansible/roles/gitlab/Readme.md
> +#### "source-endpoints"
Can we list the actual variable names? E.g.`gitlab_internal_endpoint`, ... . Same for other variables.

2022-10-13 14:28 UTC, tobigremmer-dt commented on user-skel/ansible/roles/jenkins/Readme.md
> +#### "source-endpoints"
Can we list the actual variable names?

2022-10-13 14:31 UTC, tobigremmer-dt commented on user-skel/ansible/roles/jenkins/Readme.md
> +    include_jenkins_value_file: "{{ role_path }}/templates/<use case name>-jobs.yml.j2" # rename with your use case name
Can we add a note what this set_fact does? I.e. it specifies where the Jinja template can be found.

A link to an example template would probably also help, for example https://github.com/Dynatrace/ace-box/blob/dev/user-skel/ansible/roles/demo-quality-gates-jenkins/templates/demo-default-jobs.yml.j2

2022-10-13 14:32 UTC, tobigremmer-dt commented on user-skel/ansible/roles/jenkins/Readme.md
> +    git_username: "<a git tool user name>" # set your git tool´s user name
I would make it more clear that `git_XYZ` are just examples and these are the actual variables that are substituted.

2022-10-13 14:33 UTC, tobigremmer-dt commented on user-skel/ansible/roles/keptn-cli/Readme.md
> +This currated role install Keptn CLI on the acebox.
Can we add a link to the official Keptn docs please? ( https://keptn.sh/docs/ )

2022-10-13 14:34 UTC, tobigremmer-dt commented on user-skel/ansible/roles/microk8s/Readme.md
> +It also configures kube config to automatically connect to the cluster via kubectl and helm.
Can we please add a link to the official microk8s docs?

2022-10-13 14:37 UTC, tobigremmer-dt commented on user-skel/ansible/roles/repository/Readme.md
> +  loop:
Maybe `loop` overcomplicates things here. For documentation purposes, can we simply show how these variables are usually provided?

2022-10-13 14:39 UTC, tobigremmer-dt commented on user-skel/ansible/roles/monaco/Readme.md
> +This currated role can be used to install monaco CLI on the ace-box.
Can we please add to the official Monaco docs?

2022-10-13 14:41 UTC, tobigremmer-dt requested changes
Awesome! Overall, pretty clear without being too detailed and hard to digest. Like the structure.

I flagged some minors.

2022-10-14 10:23 UTC, eemrdog commented on user-skel/ansible/roles/app-easytravel/Readme.md
> +    Easy Travel Aplication Specific:
updated

2022-10-14 10:23 UTC, eemrdog commented on user-skel/ansible/roles/dashboard/Readme.md
> +This currated role can be used to install Acebox Dashboard on a kubernetes cluster.
updated

2022-10-14 10:23 UTC, eemrdog commented on user-skel/ansible/roles/dashboard/Readme.md
> +  ```
updated

2022-10-14 10:23 UTC, eemrdog commented on user-skel/ansible/roles/dt-activegate/Readme.md
> +This currated role can be used to deploy Dynatrace Synthetic-enabled ActiveGate on the acebox.
updated

2022-10-14 10:24 UTC, eemrdog commented on user-skel/ansible/roles/dt-oneagent/Readme.md
> +This currated role can be used to deploy Dynatrace Oneagent on the acebox.
updated changing  the description to k8s operator

2022-10-14 10:25 UTC, eemrdog commented on user-skel/ansible/roles/gitea/Readme.md
> +#### "source-secret"
ok for create-secret. Could not get what you refer to sourcing endpoints? if it is for source-endpoint task, it does not have an input variable as I see

2022-10-14 10:29 UTC, eemrdog commented on user-skel/ansible/roles/gitea/Readme.md
> +#### "source-secret"
I provided "gitea_internal_endpoint" as an output variable from this task. Does it look good?

2022-10-14 10:29 UTC, eemrdog commented on user-skel/ansible/roles/gitlab/Readme.md
> +#### "source-endpoints"
added this var as output var from this task

2022-10-14 11:02 UTC, eemrdog commented on user-skel/ansible/roles/jenkins/Readme.md
> +#### "source-endpoints"
updated

2022-10-14 11:12 UTC, eemrdog commented on user-skel/ansible/roles/jenkins/Readme.md
> +    git_username: "<a git tool user name>" # set your git tool´s user name
ok I put a disclaimer that these are example key-value variables and depending on a use case, these names can change

2022-10-14 11:13 UTC, eemrdog commented on user-skel/ansible/roles/keptn-cli/Readme.md
> +This currated role install Keptn CLI on the acebox.
updated

2022-10-14 11:14 UTC, eemrdog commented on user-skel/ansible/roles/microk8s/Readme.md
> +It also configures kube config to automatically connect to the cluster via kubectl and helm.
updated

2022-10-14 11:16 UTC, eemrdog commented on user-skel/ansible/roles/repository/Readme.md
> +  loop:
yes right, makes sense. Updated

2022-10-14 11:18 UTC, eemrdog commented on user-skel/ansible/roles/monaco/Readme.md
> +This currated role can be used to install monaco CLI on the ace-box.
updated

2022-10-14 11:32 UTC, eemrdog commented on user-skel/ansible/roles/dashboard/Readme.md
> +  ```
I added expRefs, does it look good?

2022-10-14 11:32 UTC, eemrdog commented on user-skel/ansible/roles/gitlab/Readme.md
> +#### "source-endpoints"
Same as gitea, Does it look good?

2022-10-14 11:35 UTC, eemrdog commented on user-skel/ansible/roles/jenkins/Readme.md
> +    git_username: "<a git tool user name>" # set your git tool´s user name
Does it look good?

2022-10-14 11:39 UTC, eemrdog commented
@tobigremmer-dt  Could you please check only the 4 conversations to be resolved if they look good?

2022-10-14 11:42 UTC, tobigremmer-dt commented on user-skel/ansible/roles/dashboard/Readme.md
> +        extRefs:
Indentation is off here.

2022-10-14 12:01 UTC, tobigremmer-dt approved these changes
Looks great. Good job.

2022-10-14 12:04 UTC, merged