339 feature keptn role readme and other readme enhancements
Dynatrace/ace-box pull request #341
Opened 2022-10-28 13:31 UTC by eemrdog

2022-11-11 11:08 UTC, tobigremmer-dt commented on user-skel/ansible/roles/keptn/Readme.md
> +This currated role can be used to install keptn on a kubernetes cluster.
... Keptn on a Kubernetes ... -> Capitalize

2022-11-11 11:12 UTC, tobigremmer-dt requested changes
Please make sure proper nouns (e.g. Kubernetes, Keptn) are capitalized. Everything else looks good.

2022-11-29 12:09 UTC, eemrdog commented on user-skel/ansible/roles/keptn/Readme.md
> +This currated role can be used to install keptn on a kubernetes cluster.
done

2022-11-29 13:28 UTC, tobigremmer-dt approved these changes
Looks good

2022-11-29 13:29 UTC, merged