Feature/11 awx auto remediation rebase
Dynatrace/ace-box pull request #40
Opened 2021-07-14 17:03 UTC by tobigremmer-dt

Implements #20 and #11

2021-07-15 07:45 UTC, kristofre requested changes

2021-07-15 07:45 UTC, kristofre commented on microk8s/repos/auto-remediation/ace-demo-canary-docs/02-configure-dynatrace/Readme.md
> +
@tobigremmer-dt Can you add a note to show the user that the service is being served by 2 processes (v1 and v2), with a screenshot as well? This can be from the services screen

2021-07-15 07:45 UTC, kristofre commented on microk8s/repos/auto-remediation/ace-demo-canary-docs/04-shift-traffic/Readme.md
> +A playbook is run which slowly increases the percentage of traffic that is routed to the canary. With each incrementation step an event is pushed to Dynatrace to make it aware of the service's config
@tobigremmer-dt at this point I would direct the user to create a multi-dimensional analysis chart to split response time/request count/failure rate by version. To highlight that (new) capability in the platform
![image](https://user-images.githubusercontent.com/9797800/125749542-ba4adb2b-ccdb-4075-b246-0ac36913ec97.png)

2021-07-15 07:45 UTC, kristofre commented on microk8s/repos/auto-remediation/ace-demo-canary-docs/02-configure-dynatrace/Readme.md
> +![dynatrace_frequent_issue_detection](../assets/images/dynatrace_frequent_issue_detection.png)
Here I would direct the users to the Release Inventory screen, showing that both versions are detected and deployment events are showing 
![image](https://user-images.githubusercontent.com/9797800/125749253-32019242-3cdd-441c-9d4d-91a47523182d.png)

2021-07-15 07:48 UTC, kristofre commented on microk8s/repos/auto-remediation/ace-demo-canary-docs/Readme.md
> +TBD
I would leave an introduction "story" here:
Introduce the use case
Technical implementation (nginx ingress canary + awx + jenkins + DT)
Flow 
Why it is important

2021-07-15 12:32 UTC, tobigremmer-dt commented
Agreed on and implemented requested changes. @kristofre

2021-07-16 11:31 UTC, kristofre approved these changes

2021-07-16 11:46 UTC, merged