monaco config updates for app-hipstershop
Dynatrace/ace-box pull request #403
Opened 2022-12-22 08:36 UTC by eemrdog

2022-12-22 10:55 UTC, tobigremmer-dt requested changes
Added a few comments. Rest looks good.

2022-12-22 10:55 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-hipstershop/tasks/apply-dt-configuration.yml
> +# - name: Source Host Group ID
Please remove if not needed.

2022-12-22 10:55 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-hipstershop/files/monaco/projects/infrastructure/conditional-naming-service/NamespacePod.json
> + "nameFormat": "{ProcessGroup:KubernetesNamespace}.{ProcessGroup:KubernetesBasePodName}",
Please check: Does this align with our other examples/demos?

2022-12-22 10:55 UTC, tobigremmer-dt commented on user-skel/ansible/roles/app-hipstershop/files/monaco/projects/hipstershop/synthetic-monitor/hipstershop-http.json
> +  "frequencyMin": {{.frequencyInMin}},
Small linting related comment: Please try to be consistent when using whitespace, naming variables, etc. For example: `{{.frequencyInMin}}` -> `{{ .frequencyInMin }}`

2023-01-02 06:58 UTC, eemrdog commented on user-skel/ansible/roles/app-hipstershop/files/monaco/projects/infrastructure/conditional-naming-service/NamespacePod.json
> + "nameFormat": "{ProcessGroup:KubernetesNamespace}.{ProcessGroup:KubernetesBasePodName}",
Namespace - Pod Name based naming seemed to me more structured but the other examples use the ContainerName - NAmespace based naming. So, I will revert this back not to confuse the rest

2023-01-02 07:20 UTC, eemrdog commented on user-skel/ansible/roles/app-hipstershop/tasks/apply-dt-configuration.yml
> +# - name: Source Host Group ID
done

2023-01-02 07:35 UTC, eemrdog commented on user-skel/ansible/roles/app-hipstershop/files/monaco/projects/hipstershop/synthetic-monitor/hipstershop-http.json
> +  "frequencyMin": {{.frequencyInMin}},
ok

2023-01-02 07:51 UTC, tobigremmer-dt approved these changes
Looks good!

2023-01-02 08:36 UTC, merged