481 feature release validation demo based on srg
Dynatrace/ace-box pull request #498
Opened 2023-06-16 14:58 UTC by eemrdog

2023-06-27 08:46 UTC, tobigremmer-dt requested changes
Temporary review to fix the first batch of issues.

2023-06-27 08:46 UTC, tobigremmer-dt commented on Readme.md
> +        | use_case | string | no | Use case, the ACE Box will be prepared for. Options are:<ul> <li>`demo_default` (Default)</li><li>`demo_quality_gates_jenkins`</li><li>`demo_security_gates_jenkins`
Link doesn't work.

2023-06-27 08:46 UTC, tobigremmer-dt commented on Readme.md
> +        | use_case | string | no | Use case, the ACE Box will be prepared for. Options are:<ul> <li>`demo_default` (Default)</li><li>`demo_quality_gates_jenkins`</li><li>`demo_security_gates_jenkins`
Also, please add details to `Available use cases` below. (This was missed for the AR demo as well)

2023-06-27 08:46 UTC, tobigremmer-dt commented on Readme.md
> +         \*: `demo_release_validation_srg_gitlab` requires extra variables. See [use case README](user-skel/ansible/roles/demo-release_validation-srg-gitlab/README.md) for details.
Line break doesn't work, i.e. not displayed correctly.

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/defaults/main.yml
> +gitlab_demo_default_group: "demo"
Please make defaults more use case specific to prevent conflicts, e.g. `dt_rv_srg_gitlab_group`

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +- name: Overwrite .gitlab-ci.yml
Can all of this be added to `app_simplenode_overwrites` ? Would make it much cleaner....

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +- name: Publish docs
How do you feel about merging docs and simplenode repo so that we only have one and users don't have to jump back and forth?

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +---
Please add cleanup task, i.e. destroy all potentially conflicting Monaco resources.

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/monaco/manifest.yaml
> +  - name: app
What's the rationale behind splitting staging and prod apps (opposed to e.g. Monaco's enviromentGroups options)?

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/.gitlab-ci.yml
> +4-monaco-prod:
Neither Monaco prod nor sending events fails when the SRG step fails.

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/monaco/manifest.yaml
> +  - name: app
Also, why is there a dedicated SRG project? Wouldn't that be part of the (staging) app?

2023-06-27 08:46 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/.gitlab-ci.yml
> +3-monaco-srg:
This step currently fails with:
![Screenshot 2023-06-27 at 10 43 39 AM](https://github.com/Dynatrace/ace-box/assets/83594825/687417f8-aef5-4205-81a1-4b9956ed1921)

2023-06-27 09:29 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/monaco/manifest.yaml
> +  - name: app
For reference: https://github.com/dynatrace-ace/ace-box-ext-is-architect-workshop/tree/main/roles/my-use-case/files/simplenode

2023-06-28 06:25 UTC, tobigremmer-dt commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/.gitlab-ci.yml
> +3-monaco-srg:
Confirmed this is a platform issue which is currently being fixed.

2023-06-28 10:33 UTC, eemrdog commented on Readme.md
> +        | use_case | string | no | Use case, the ACE Box will be prepared for. Options are:<ul> <li>`demo_default` (Default)</li><li>`demo_quality_gates_jenkins`</li><li>`demo_security_gates_jenkins`
link is working now and added the ar and srg use cases under the available use cases section with their readme links

2023-06-28 10:33 UTC, eemrdog commented on Readme.md
> +         \*: `demo_release_validation_srg_gitlab` requires extra variables. See [use case README](user-skel/ansible/roles/demo-release_validation-srg-gitlab/README.md) for details.
fixed

2023-06-28 10:41 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/defaults/main.yml
> +gitlab_demo_default_group: "demo"
done

2023-06-28 11:33 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +- name: Publish docs
I separated to make it as the same structure with ar use case, but makes more sense to me to merge them. I also merged the simplenode deployment explanations- the distilled version- into the demo use case documentation

2023-06-28 12:01 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +---
added this into the code and will be tested

2023-06-29 11:20 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/tasks/main.yml
> +- name: Overwrite .gitlab-ci.yml
fixed the overwrite problem and working now

2023-06-29 11:22 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/monaco/manifest.yaml
> +  - name: app
- two dt envs defined as staging and production in the monaco manifest file
- merged the srg and app deployment in the same gitlab job for staging env
- dt prod configuration is separated from them using the env groups

2023-06-29 11:25 UTC, eemrdog commented on user-skel/ansible/roles/demo-release-validation-srg-gitlab/files/.gitlab-ci.yml
> +4-monaco-prod:
resolved with the new pipeline stage structure, monaco event for staging is dependent with monaco staging, same holds true for srg and prod

2023-07-28 13:12 UTC, tobigremmer-dt approved these changes
Looks good

2023-07-30 22:34 UTC, merged