Feature/edge connect
Dynatrace/ace-box pull request #730
Opened 2024-10-30 13:36 UTC by IgnacioGoldman

deploys edge-connect

2024-10-30 16:15 UTC, drqc requested changes

2024-10-30 16:15 UTC, drqc commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/templates/edgeconnect.yaml.j2
> +apiVersion: dynatrace.com/v1alpha1
is it possible to specify a static version and put that as a var that can be overwritten

2024-11-05 11:12 UTC, kristofre commented
@IgnacioGoldman there are multiple changes for easytrade also in this PR - they should be separated

Also, please link an issue that this PR would address

2024-11-07 00:03 UTC, drqc commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/templates/edgeconnect.yaml.j2
> +apiVersion: dynatrace.com/v1alpha1
seems like recommended practice from dt docs is to use latest

2024-11-07 00:03 UTC, drqc approved these changes

2024-11-07 09:23 UTC, kristofre requested changes

2024-11-07 09:23 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/gitlab-k8s-workflow-credentials.yaml
> +- name: Gitlab - Additional Environment Variables
This task seems out of place. Since Gitlab is the tool that is being modified, the task belongs in the gitlab role.

My suggestion would be that we have a task in the edge connect role that generates the data.
The Gitlab role then has a task that requests from edge connect the info and then adds it

2024-11-07 10:40 UTC, IgnacioGoldman commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/gitlab-k8s-workflow-credentials.yaml
> +- name: Gitlab - Additional Environment Variables
Good point,

Now the task generates the variables independently the use. I've described it in the readme on how to use it.

2024-11-26 08:04 UTC, kristofre requested changes
Please take a look at the comments

2024-11-26 08:04 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/Readme.md
> +- include_role:
This is confusing. It seems here that you first need to call
```yaml
- include_role:
    name: dt-operator
```

And then you need to install the operator:
```yaml
- include_role:
    name: dt-operator
  vars:
    edge_connect: true
```

I assume this can be done in one go?

2024-11-26 08:04 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/Readme.md
> +The credentials can be used in your Ansible code (I.e. set them as environment variables in Gitlab) with the following values:
Can we please use code blocks as examples?

2024-11-26 08:04 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/generate-credentials.yaml
> +    kubectl get namespace kube-system --output jsonpath={.metadata.uid}
Please use ansible modules to interact with Kubernetes https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html

```yaml
- name: Get an existing Service object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: kube-system
  ...
```

2024-11-26 08:04 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/main.yaml
> +- name: Request a DT OAuth access token
Please use the ACE-Box `dt-oauth-token` role...

2024-11-27 12:29 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/main.yaml
> +# https://dynatrace-docs-preview.spine-dev.internal.dynatracelabs.com/pr-1966/docs/setup-and-configuration/setup-on-k8s/guides/operation/edgeconnect/edge-connect-provision#create-oauth-client
For Open Source - we cannot link internal DT info

2024-11-27 12:29 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/main.yaml
> +# https://dynatrace-docs-preview.spine-dev.internal.dynatracelabs.com/pr-1966/docs/platform-modules/automations/workflows/actions/kubernetes-automation/kubernetes-workflows-setup#define-service-accou
Same as other comment - no internal docs

2024-11-27 12:30 UTC, kristofre commented on user-skel/ansible_collections/ace_box/ace_box/roles/edge-connect/tasks/generate-credentials.yaml
> +- name: Configure k8s workflow action connector setting
Can this be done via Monaco?

2024-11-29 12:08 UTC, kristofre approved these changes

2024-11-29 15:20 UTC, merged