Feature/fuentbit
Dynatrace/ace-box pull request #731
Opened 2024-10-30 13:39 UTC by IgnacioGoldman

fluentbit collector for logs

2024-10-30 16:13 UTC, drqc requested changes
a couple of questions: is there a way to set the ed-ge connect version and also the fluentbit version should be static. I'm guessing you are moving the edge connect + fluent bit together in the same PR because are used together?

2024-10-30 16:13 UTC, drqc commented on user-skel/ansible_collections/ace_box/ace_box/roles/fluentbit/tasks/main.yml
> +    chart_ref: fluent/fluent-bit
we should set the fluentbit version for this install step. You can use as an example this 
 kubernetes.core.helm:
    name: "otel-demo"
    chart_ref: open-telemetry/opentelemetry-demo
    chart_version: "{{ otel_helm_chart_version }}"

2024-11-05 11:14 UTC, kristofre commented
@IgnacioGoldman this PR covers changes on easytrade, edgeconnect and fluentbit. Please separate those out, also please link the issue that the PR addresses/closes

2024-11-06 23:53 UTC, drqc approved these changes
the files lgtm, if you could link it to the issue so we have track in the relation between the issues and PR's

2024-11-07 09:45 UTC, merged