Documentation update
Dynatrace/ace-box pull request #732
Opened 2024-11-06 11:20 UTC by IgnacioGoldman

general and detailed use-case developer ace-box documentation enhancement

2024-11-06 13:36 UTC, kristofre commented on Readme.md
> +| ace-box-ext-demo-auto-remediation-easytravel | An auto remediation demo using Dynatrace, ServiceNow and Ansible | [here](https://github.com/dynatrace-ace/ace-box-ext-demo-auto-remediation-easytrave
this is a gen2 demo which hasn't been maintained for 2y, we should not reference it

2024-11-06 13:47 UTC, kristofre commented on Readme.md
> +| ace-box-sandbox-easytravel                   | A simple ACE-Box with EasyTravel monitored by Dynatrace          | [here](https://github.com/dynatrace-ace/ace-box-sandbox-easytravel) | [here](https:
This use case does not deploy anymore as the easytravel saw it's Monaco config deleted (see with @eemrdog )

2024-11-26 08:14 UTC, kristofre requested changes

2024-11-26 08:14 UTC, kristofre commented on docs/custom-use-case.md
> +    ace enable https://github.com/dynatrace-ace/basic-dt-demo.git --local
Please explain what `--local` does (not clone the repo, not push any changes, ...)

2024-11-26 08:14 UTC, kristofre commented on docs/custom-use-case.md
> +        easytrade_namespace: "easytrade-app"
Variables are used but not introduced at all.

Please ensure that the audience understand how/where variables like `ingress_domain` come from and how people can understand which variables are used for `app-easytrade` for example.

2024-11-26 08:14 UTC, kristofre commented on docs/custom-use-case.md
> +10. Let's add a demo app. Repeat step `8` & `9`, but this time following the [app-easytrade](https://github.com/Dynatrace/ace-box/tree/dev/user-skel/ansible_collections/ace_box/ace_box/roles/app-easy
Two times number 10

2024-11-26 08:14 UTC, kristofre commented on docs/custom-use-case.md
> +Check out the OOTB roles [ReadMe](/user-skel/ansible_collections/ace_box/ace_box/roles/Readme.md) for the complete list of Ansible roles natively provided by the ACE-Box framework.
This list is not complete.

We need a guide that explains people how to interact with a role

2024-11-27 14:22 UTC, Eugenio-DT commented on docs/custom-use-case.md
> +10. Let's add a demo app. Repeat step `8` & `9`, but this time following the [app-easytrade](https://github.com/Dynatrace/ace-box/tree/dev/user-skel/ansible_collections/ace_box/ace_box/roles/app-easy
Fixed

2024-11-27 14:23 UTC, Eugenio-DT commented on docs/custom-use-case.md
> +        easytrade_namespace: "easytrade-app"
For sake of simplicity, we removed the ansible variables and added a specific section to cover and explain their usage within the Get Pro section

2024-11-27 14:23 UTC, Eugenio-DT commented on docs/custom-use-case.md
> +    ace enable https://github.com/dynatrace-ace/basic-dt-demo.git --local
Great point. Added.

2024-11-27 14:28 UTC, Eugenio-DT commented on docs/custom-use-case.md
> +Check out the OOTB roles [ReadMe](/user-skel/ansible_collections/ace_box/ace_box/roles/Readme.md) for the complete list of Ansible roles natively provided by the ACE-Box framework.
Agreed for the list, we'll work on it.

As regards role usage, we have pointed to the role-specific readme file (placed within the folder where the role is defined), since there it is the right place to specify how the role can be used and how to interact with it.

Also added an example to clarify.

2024-11-28 15:34 UTC, kristofre approved these changes

2024-11-29 15:23 UTC, merged