765 dt operator fluentbit collector disabled by default
Dynatrace/ace-box pull request #766
Opened 2024-12-05 14:57 UTC by IgnacioGoldman

Fluentbit log_monitoring default variable disabled. ACE-Box users ran into issues with fluentbit collector when it wasn't initially necessary for them.

2024-12-10 13:06 UTC, eemrdog requested changes
can we change the dt-operator with a GA version?

2024-12-10 13:06 UTC, eemrdog commented on user-skel/ansible_collections/ace_box/ace_box/roles/dt-operator/defaults/main.yml
>  operator_mode: "applicationMonitoring"  # default & prefered deployment option
what about changing the operator version with a GA version?

2024-12-11 08:37 UTC, IgnacioGoldman commented on user-skel/ansible_collections/ace_box/ace_box/roles/dt-operator/defaults/main.yml
>  operator_mode: "applicationMonitoring"  # default & prefered deployment option
I will do push that in a separate PR, I've do to some testing first

2024-12-11 09:16 UTC, eemrdog commented on user-skel/ansible_collections/ace_box/ace_box/roles/dt-operator/defaults/main.yml
>  operator_mode: "applicationMonitoring"  # default & prefered deployment option
ok thanks, there is another open issue for that

2024-12-11 09:16 UTC, eemrdog approved these changes

2024-12-12 09:23 UTC, merged